### PR TITLE
 Make more react properties available to dash

### PR DESCRIPTION
**Pull request by keivan-sl**
Attempting to make other `react-datetime` properties available to the Dash component. Solving the issue #2

### CODE REVIEW

**Comment by keivan-sl** [comment]
@SebastianRehfeldt I have added the `utc` and `locale` properties and tested them as well. They seem to work as expected for me. Let me know if you want me to change anything else in the PR.

**Comment by SebastianRehfeldt** [comment]
Hey @keivan-sl thanks for the PR, I want to give it a quick test myself and hope to have some time later this week. There are some files changed due to running `npm start`. I have not thoroughly thought about which files should be kept in the repository and thus be included in PRs. So no need to remove them from the PR. I think the essential changes would have been in:
- DashDatetimepicker.react.js
- usage.py

The rest should be autogenerated files after local development.

**Comment by keivan-sl** [comment]
@SebastianRehfeldt Yes you are correct, even I had my doubts while uploading. The changes are limited to the 2 files, everything else is auto-generated.

**Comment by SebastianRehfeldt** [comment]
LGTM - will merge and then create a new release. Thansk @keivan-sl

**Pull request merged**
