### PR TITLE
Make more react properties available to dash

### PR DESCRIPTION
**Pull request by keivan-sl**
Attempting to make other [react-datetime](https://github.com/arqex/react-datetime) properties available to the Dash component. Solving the issue #2

### CODE REVIEW

**Comment by keivan-sl** [comment]
I have only added the `utc` property for now, although it seems to be working as intended to me, it does give some errors while running `npm start` 
```log
> npm start
...
Error: Exited with code 3
    at ChildProcess.<anonymous> (/app/dash_datetimepicker/node_modules/opn/index.js:85:13)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:400:28)
    at Pipe.<anonymous> (net.js:675:12)
```
This is my first time working with dash components as well as npm/react so I am not sure what mistakes I might be making. If anyone can help me solve or point me the correct direction, I would like to solve the issues and contribute to the repo. 

Thanks.
Keivan Shah.

**Comment by SebastianRehfeldt** [comment]
Hi @keivan-sl !
Thanks for your contribution. It's some long time ago that I implemented this dash component but I think I've seen the same issue myself. I would need to have a closer look to help you with this though. I might have some time this week for this and let you know.
Regarding bumping the version to `0.0.5` I would rather not do this within this MR. As I would like to fix the dependency warnings first and then include both things in the next version.

**Comment by keivan-sl** [comment]
Hey @SebastianRehfeldt, Thanks for the quick reply! 
You are right, the version bump is not suited for this MR. I only did that so that I can distinguish my version of the package from the PyPI package. I will roll that back the version upgrade. Let me know if you take a closer look and find out the issue.

**Comment by SebastianRehfeldt** [comment]
I had some time now to check the issue with `npm start`. It seems to me that `opn` is used to automatically open a browser which will most likely not work as we use docker for developing the datepicker. It can safely be ignored and also prevented by updating the `start` script in the `package.json` to:

```
"start": "webpack-serve --config ./webpack.serve.config.js",
```

Wrt. your MR I think the required changes to expose the new parameter are in:
- `dash_datetimepicker/src/lib/components/DashDatetimepicker.react.js`
- `dash_datetimepicker/usage.py`

I would rather bump the version and update all the build files in a separate PR/commit and also use this opportunity to update the requirements. I still want to give it a quick test with the utc parameter. Otherwise happy to approve if you remove the build/version-bump files from the PR.

**Comment by keivan-sl** [comment]
Hey @SebastianRehfeldt ! Thanks for debugging the issue. I will undo the version bump and see if I can add more properties (eg: `locale`) to the component. I am busy with work in the weekdays so will probably look this up over the weekends.

**Comment by SebastianRehfeldt** [comment]
Sounds like a plan! I'll try to find some time this week to open a PR to update dependencies and fix the start script. Regarding additional properties, feel free to add more if you have time. The `locale` in the issue was just a suggestion. The datepicker of this repository included only the very minimal amount of properties that we needed at work for a basic monitoring page.  As we dont actively develop it anymore, this repository is not actively maintained but I can at least offer to review PRs and push new versions to pypi from time to time

**Comment by SebastianRehfeldt** [comment]
Hey @keivan-sl , I updated the dependencies, fixed the start script and made a new release. Feel free to finish this PR whenever you have time and I can do another release once merged

**Comment by keivan-sl** [comment]
Hey @SebastianRehfeldt ! Awesome, I will create a new PR based on the latest master. Closing this PR for now.

**Pull request closed without merging**
